### PR TITLE
feat: fix overflow in /metrics/validators and add denom exponent

### PR DESCRIPTION
**Pull request by v-shash**
- Fix overflow when delegator tokens too large for /metrics/validators endpoint
- Add denom exponent to allow for easier custom denom definition
- Add documentation for denom exponent and coefficient to avoid confusion

closed: #10

### CODE REVIEW

**Comment by freak12techno** [comment]
LGTM. Can I merge?

**Review by freak12techno — APPROVED** [review]

**Comment by mofhusseini** [comment]
> LGTM. Can I merge?

Yes. Thanks!

**Comment by freak12techno** [comment]
Sorry, forgot it. Thanks for contributing!

**Comment by AndreMiras** [comment]
Could we make a 0.3.1 release that includes that fix?

**Pull request merged**
